services:
  postgres:
    image: postgres:16-alpine
    container_name: billing-postgres
    command: ["postgres", "-c", "wal_level=logical"]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=billing_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: billing-redis
    ports:
      - "6379:6379"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: billing-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Generated random UUID for KRaft cluster format
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: billing-kafka-ui
    ports:
      - "8089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME=billing-connect
      - KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS=http://connect:8083
    depends_on:
      - kafka
      - connect

  connect:
    image: debezium/connect:2.5
    container_name: billing-connect
    ports:
      - "8087:8083"
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=billing-connect-group
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
      - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONFIG_STORAGE_REPLICATION_FACTOR=1
      - OFFSET_STORAGE_REPLICATION_FACTOR=1
      - STATUS_STORAGE_REPLICATION_FACTOR=1
      - CONNECT_REST_EXTENSION_CLASSES=
    depends_on:
      - kafka
      - postgres

  register-connector:
    image: curlimages/curl:latest
    container_name: register-debezium-connector
    volumes:
      - ./docs/debezium-outbox-connector.json:/debezium-outbox-connector.json
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        echo "Waiting for Kafka Connect to start..."
        until curl -s -o /dev/null -w "%{http_code}" http://connect:8083/connectors | grep -q "200"; do
          sleep 5
        done
        echo "Kafka Connect is ready. Registering Debezium Outbox connector..."
        curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" http://connect:8083/connectors -d @/debezium-outbox-connector.json
        echo "Connector registered successfully!"
    depends_on:
      - connect

  debezium-ui:
    image: debezium/debezium-ui:2.5
    platform: linux/amd64
    container_name: billing-debezium-ui
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
    depends_on:
      - connect

volumes:
  pgdata:
