-- =========================================================================
-- IMPORTED DMUC DATA v1.0 (Effective Date: 2025-05-10)
-- Generated automatically by Antigravity AI Agent
-- =========================================================================

-- 1. Setup tables
CREATE TABLE IF NOT EXISTS cau_hinh_cosfi (
    hs_cosfi            DECIMAL(3,2) PRIMARY KEY,
    kcosfi              DECIMAL(5,2) NOT NULL,
    ngay_adung          DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ty_gia (
    ma_dviqly           VARCHAR(6) NOT NULL,
    id_ty_gia           INT NOT NULL,
    loai_tien           VARCHAR(5) NOT NULL,
    tygia_qdoi          DECIMAL(10,2) NOT NULL,
    thang               INT NOT NULL,
    nam                 INT NOT NULL,
    ngay_nhap           TIMESTAMP NOT NULL,
    PRIMARY KEY (ma_dviqly, loai_tien, thang, nam)
);

CREATE TABLE IF NOT EXISTS cau_hinh_thue (
    loai_thue           VARCHAR(50) PRIMARY KEY,
    thue_suat           DECIMAL(5,4) NOT NULL,
    ngay_adung          DATE NOT NULL
);

-- 2. Seeding Cosphi Config
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.9, 0.0, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.59, 52.54, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.6, 50.0, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.61, 47.54, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.62, 45.16, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.63, 42.86, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.64, 40.63, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.65, 38.46, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.66, 36.36, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.67, 34.33, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.68, 32.35, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.69, 30.43, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.7, 28.57, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.71, 26.76, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.72, 25.0, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.73, 23.29, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.74, 21.62, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.75, 20.0, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.76, 18.42, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.77, 16.88, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.78, 15.38, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.79, 13.92, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.8, 12.5, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.81, 11.11, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.82, 9.76, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.83, 8.43, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.84, 7.14, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.85, 5.88, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.86, 4.65, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.87, 3.45, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.88, 2.27, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;
INSERT INTO cau_hinh_cosfi (hs_cosfi, kcosfi, ngay_adung) VALUES (0.89, 1.12, '2014-12-10') ON CONFLICT (hs_cosfi) DO UPDATE SET kcosfi = EXCLUDED.kcosfi, ngay_adung = EXCLUDED.ngay_adung;

-- 3. Seeding Exchange Rates
INSERT INTO ty_gia (ma_dviqly, id_ty_gia, loai_tien, tygia_qdoi, thang, nam, ngay_nhap) VALUES ('PD0600', 164, 'USD', 29090.0, 3, 2026, '2024-12-27 00:00:00') ON CONFLICT (ma_dviqly, loai_tien, thang, nam) DO UPDATE SET id_ty_gia = EXCLUDED.id_ty_gia, tygia_qdoi = EXCLUDED.tygia_qdoi, ngay_nhap = EXCLUDED.ngay_nhap;

-- 3b. Seeding Tax Config
INSERT INTO cau_hinh_thue (loai_thue, thue_suat, ngay_adung) VALUES ('VAT', 0.08, '2024-01-01') ON CONFLICT (loai_thue) DO UPDATE SET thue_suat = EXCLUDED.thue_suat, ngay_adung = EXCLUDED.ngay_adung;

-- 4. Seeding Stepping Tariffs
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBH_CAPDA2_20250510', 'SHBH - Bán buôn khu TT-huyện lỵ - MBA của bên mua  ', 'STEPPING', 'SHBH', '2', 'A', 'KT', true, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": 50.0, "unitPrice": 1762.0, "touPeriod": "NORMAL"}, {"step": 2, "minKwh": 50.0, "maxKwh": 100.0, "unitPrice": 1828.0, "touPeriod": "NORMAL"}, {"step": 3, "minKwh": 100.0, "maxKwh": 200.0, "unitPrice": 2017.0, "touPeriod": "NORMAL"}, {"step": 4, "minKwh": 200.0, "maxKwh": 300.0, "unitPrice": 2503.0, "touPeriod": "NORMAL"}, {"step": 5, "minKwh": 300.0, "maxKwh": 400.0, "unitPrice": 2834.0, "touPeriod": "NORMAL"}, {"step": 6, "minKwh": 400.0, "maxKwh": null, "unitPrice": 2929.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBL_CAPDA2_20250510', 'SHBL - Bán buôn khu TT-huyện lỵ - MBA của bên bán  ', 'STEPPING', 'SHBL', '2', 'A', 'KT', true, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": 50.0, "unitPrice": 1790.0, "touPeriod": "NORMAL"}, {"step": 2, "minKwh": 50.0, "maxKwh": 100.0, "unitPrice": 1856.0, "touPeriod": "NORMAL"}, {"step": 3, "minKwh": 100.0, "maxKwh": 200.0, "unitPrice": 2062.0, "touPeriod": "NORMAL"}, {"step": 4, "minKwh": 200.0, "maxKwh": 300.0, "unitPrice": 2611.0, "touPeriod": "NORMAL"}, {"step": 5, "minKwh": 300.0, "maxKwh": 400.0, "unitPrice": 2937.0, "touPeriod": "NORMAL"}, {"step": 6, "minKwh": 400.0, "maxKwh": null, "unitPrice": 3035.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHTM_CAPDA2_20250510', 'SHTM - Bán buôn khu đô thị mới   ', 'STEPPING', 'SHTM', '2', 'A', 'KT', true, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": 50.0, "unitPrice": 1947.0, "touPeriod": "NORMAL"}, {"step": 2, "minKwh": 50.0, "maxKwh": 100.0, "unitPrice": 2011.0, "touPeriod": "NORMAL"}, {"step": 3, "minKwh": 100.0, "maxKwh": 200.0, "unitPrice": 2334.0, "touPeriod": "NORMAL"}, {"step": 4, "minKwh": 200.0, "maxKwh": 300.0, "unitPrice": 2941.0, "touPeriod": "NORMAL"}, {"step": 5, "minKwh": 300.0, "maxKwh": 400.0, "unitPrice": 3286.0, "touPeriod": "NORMAL"}, {"step": 6, "minKwh": 400.0, "maxKwh": null, "unitPrice": 3393.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBT_CAPDA2_20250510', 'SHBT - Giá bán điện sinh hoạt bậc thang   ', 'STEPPING', 'SHBT', '2', 'A', 'KT', true, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": 50.0, "unitPrice": 1984.0, "touPeriod": "NORMAL"}, {"step": 2, "minKwh": 50.0, "maxKwh": 100.0, "unitPrice": 2050.0, "touPeriod": "NORMAL"}, {"step": 3, "minKwh": 100.0, "maxKwh": 200.0, "unitPrice": 2380.0, "touPeriod": "NORMAL"}, {"step": 4, "minKwh": 200.0, "maxKwh": 300.0, "unitPrice": 2998.0, "touPeriod": "NORMAL"}, {"step": 5, "minKwh": 300.0, "maxKwh": 400.0, "unitPrice": 3350.0, "touPeriod": "NORMAL"}, {"step": 6, "minKwh": 400.0, "maxKwh": null, "unitPrice": 3460.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBT_D_CAPDA2_20250510', 'SHBT - Giá bán lẻ sinh hoạt bậc D phẳng', 'FLAT', 'SHBT', '2', 'D', 'KT', false, 2017.00, '2025-05-10', 'QD 2025/QD-DMUC', null) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBB_CAPDA2_20250510', 'SHBB - Giá bán buôn phục vụ mục đích sinh hoạt       ', 'STEPPING', 'SHBB', '2', 'A', 'KT', true, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": 50.0, "unitPrice": 1658.0, "touPeriod": "NORMAL"}, {"step": 2, "minKwh": 50.0, "maxKwh": 100.0, "unitPrice": 1724.0, "touPeriod": "NORMAL"}, {"step": 3, "minKwh": 100.0, "maxKwh": 200.0, "unitPrice": 1876.0, "touPeriod": "NORMAL"}, {"step": 4, "minKwh": 200.0, "maxKwh": 300.0, "unitPrice": 2327.0, "touPeriod": "NORMAL"}, {"step": 5, "minKwh": 300.0, "maxKwh": 400.0, "unitPrice": 2635.0, "touPeriod": "NORMAL"}, {"step": 6, "minKwh": 400.0, "maxKwh": null, "unitPrice": 2744.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBC_CAPDA2_20250510', 'SHBC - Bán buôn khu TT - thành thị - MBA của bên mua ', 'STEPPING', 'SHBC', '2', 'A', 'KT', true, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": 50.0, "unitPrice": 1826.0, "touPeriod": "NORMAL"}, {"step": 2, "minKwh": 50.0, "maxKwh": 100.0, "unitPrice": 1892.0, "touPeriod": "NORMAL"}, {"step": 3, "minKwh": 100.0, "maxKwh": 200.0, "unitPrice": 2109.0, "touPeriod": "NORMAL"}, {"step": 4, "minKwh": 200.0, "maxKwh": 300.0, "unitPrice": 2667.0, "touPeriod": "NORMAL"}, {"step": 5, "minKwh": 300.0, "maxKwh": 400.0, "unitPrice": 2999.0, "touPeriod": "NORMAL"}, {"step": 6, "minKwh": 400.0, "maxKwh": null, "unitPrice": 3134.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBD_CAPDA2_20250510', 'SHBD - Bán buôn khu TT - thành thị - MBA của bên bán ', 'STEPPING', 'SHBD', '2', 'A', 'KT', true, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": 50.0, "unitPrice": 1853.0, "touPeriod": "NORMAL"}, {"step": 2, "minKwh": 50.0, "maxKwh": 100.0, "unitPrice": 1919.0, "touPeriod": "NORMAL"}, {"step": 3, "minKwh": 100.0, "maxKwh": 200.0, "unitPrice": 2172.0, "touPeriod": "NORMAL"}, {"step": 4, "minKwh": 200.0, "maxKwh": 300.0, "unitPrice": 2750.0, "touPeriod": "NORMAL"}, {"step": 5, "minKwh": 300.0, "maxKwh": 400.0, "unitPrice": 3102.0, "touPeriod": "NORMAL"}, {"step": 6, "minKwh": 400.0, "maxKwh": null, "unitPrice": 3206.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;

-- 5. Seeding Grouped FLAT/TOU Tariffs
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SXCN_CAPDA8_20250510', 'SXCN - Bán buôn KCN tại thanh cái 110KV - Dung lượng MBA>100MVA - Giờ CD   ', 'TOU', 'SXCN', '8', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3197.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1117.0, "touPeriod": "OFF_PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1728.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3164.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1079.0, "touPeriod": "OFF_PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1737.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3183.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1084.0, "touPeriod": "OFF_PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1744.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SXBT_CAPDA2_20250510', 'SXBT - SXBT - Cấp điện áp dưới 6KV - Giờ BT          ', 'TOU', 'SXBT', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1987.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3640.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1300.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SXBT_CAPDA4_20250510', 'SXBT - SXBT - Cấp điện áp từ 6KV đến dưới 22KV - Giờ BT         ', 'TOU', 'SXBT', '4', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1899.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3508.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1234.0, "touPeriod": "OFF_PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1865.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3441.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1210.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SXBT_CAPDA7_20250510', 'SXBT - Cấp điện áp từ 22KV đến dưới 110KV - Giờ BT       ', 'TOU', 'SXBT', '7', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1833.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3398.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1190.0, "touPeriod": "OFF_PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1800.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3334.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1168.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SXBT_CAPDA8_20250510', 'SXBT - Cấp điện áp từ 110KV trở lên - Giờ BT', 'TOU', 'SXBT', '8', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1811.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3266.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1146.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBT_TT_CAPDA2_20250510', 'SHBT - Giá bán lẻ điện sinh hoạt bậc thang  theo hình thức trả trước', 'TOU', 'SHBT', '2', 'A', 'TT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2909.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1984.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2050.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2380.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2998.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3350.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3460.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBH_CAPDA2_20250510', 'SHBH - Bán buôn khu TT-huyện lỵ - MBA của bên mua - Cho 50 kWh đầu tiên', 'TOU', 'SHBH', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1762.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1828.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2017.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2503.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2834.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2929.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1750.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBL_CAPDA2_20250510', 'SHBL - Bán buôn khu TT-huyện lỵ - MBA của bên bán - Cho 50 kWh đầu tiên    ', 'TOU', 'SHBL', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1790.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1856.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2062.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2611.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2937.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3035.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1750.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_KDBB_CAPDA2_20250510', 'KDBB - Giá bán buôn cho chợ', 'FLAT', 'KDBB', '2', 'A', 'BT', false, 2818.0, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2818.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_LTDL_CAPDA2_20250510', 'LTDL - LTDL - Cấp điện áp dưới 6KV - Giờ BT          ', 'TOU', 'LTDL', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3152.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5422.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1918.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_LTDL_CAPDA4_20250510', 'LTDL - LTDL - Cấp điện áp từ 6KV đến dưới 22KV - Giờ BT         ', 'TOU', 'LTDL', '4', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3108.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5202.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1829.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_LTDL_CAPDA7_20250510', 'LTDL - LTDL-Cấp điện áp từ 22KV đến dưới 110KV - Giờ BT       ', 'TOU', 'LTDL', '7', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2887.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5025.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1609.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_LTDL_CAPDA8_20250510', 'LTDL - LTDL-Cấp điện áp từ 110KV trở lên - Giờ BT', 'TOU', 'LTDL', '8', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2887.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5025.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1609.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_BBUA_CAPDA2_20250510', 'BBUA - Giá bán điện của CPC, NPC cho Lào', 'FLAT', 'BBUA', '2', 'A', 'BT', false, 0.112, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 0.112, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_BBUC_CAPDA2_20250510', 'BBUC - Giá bán điện của EVNCPC cho Campuchia', 'FLAT', 'BBUC', '2', 'A', 'BT', false, 0.135, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 0.135, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_BBUB_CAPDA2_20250510', 'BBUB - Giá bán điện của EVNSPC cho Campuchia', 'FLAT', 'BBUB', '2', 'A', 'BT', false, 0.135, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 0.135, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBD_CAPDA2_20250510', 'SHBD - Bán buôn khu TT - thành thị - MBA của bên bán - Cho kWh từ 201 - 300  ', 'TOU', 'SHBD', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2750.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3102.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3206.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1750.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1853.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1919.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2172.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHTM_CAPDA2_20250510', 'SHTM - Bán buôn điện sinh hoạt cho tổ hợp TM-DV-SH Cho 50 kWh đầu tiên     ', 'TOU', 'SHTM', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1947.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2011.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2334.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2941.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3286.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3393.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2989.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5140.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1818.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_CQBV_CAPDA2_20250510', 'CQBV - CQBV -Cấp điện áp dưới 6kV', 'FLAT', 'CQBV', '2', 'A', 'BT', false, 2072.0, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2072.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_CQBV_CAPDA8_20250510', 'CQBV - CQBV -Cấp điện áp từ 6kV trở lên', 'FLAT', 'CQBV', '8', 'A', 'BT', false, 1940.0, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1940.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_CQHC_CAPDA2_20250510', 'CQHC - CQHC -Cấp điện áp dưới 6kV', 'FLAT', 'CQHC', '2', 'A', 'BT', false, 2226.0, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2226.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_CQHC_CAPDA8_20250510', 'CQHC - CQHC -Cấp điện áp từ 6kV trở lên', 'FLAT', 'CQHC', '8', 'A', 'BT', false, 2138.0, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2138.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_KDDV_CAPDA2_20250510', 'KDDV - KDDV Cấp điện áp dưới 6KV - Giờ BT ', 'TOU', 'KDDV', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3152.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5422.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1918.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_KDDV_CAPDA4_20250510', 'KDDV - KDDV Cấp điện áp từ 6 kV đến dưới 22 kV - Giờ BT   ', 'TOU', 'KDDV', '4', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3108.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5202.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1829.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_KDDV_CAPDA8_20250510', 'KDDV - KDDV Cấp điện áp từ 22 kV trở lên- Giờ BT      ', 'TOU', 'KDDV', '8', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2887.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 5025.0, "touPeriod": "PEAK"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1609.0, "touPeriod": "OFF_PEAK"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBB_CAPDA2_20250510', 'SHBB - SHBB Cho 50 kWh đầu tiên  ', 'TOU', 'SHBB', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1658.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1724.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1876.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2327.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2635.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2744.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1735.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
INSERT INTO bieu_gia (ma_bieu_gia, ten_bieu_gia, loai_bieu_gia, ma_nhomnn, khoang_da, ma_ngia_cmis, thoigian_bdien, bac_thang, don_gia_phang, ngay_hieu_luc, quyet_dinh_phap_ly, chi_tiet_gia) VALUES ('TARIFF_SHBC_CAPDA2_20250510', 'SHBC - Bán buôn khu TT - thành thị - MBA của bên mua - Cho 50 kWh đầu tiên   ', 'TOU', 'SHBC', '2', 'A', 'BT', false, null, '2025-05-10', 'QD 2025/QD-DMUC', '[{"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1826.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1892.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2109.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2667.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 2999.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 3134.0, "touPeriod": "NORMAL"}, {"step": 1, "minKwh": 0.0, "maxKwh": null, "unitPrice": 1750.0, "touPeriod": "NORMAL"}]'::jsonb) ON CONFLICT (ma_bieu_gia) DO UPDATE SET ten_bieu_gia = EXCLUDED.ten_bieu_gia, loai_bieu_gia = EXCLUDED.loai_bieu_gia, ma_nhomnn = EXCLUDED.ma_nhomnn, khoang_da = EXCLUDED.khoang_da, ma_ngia_cmis = EXCLUDED.ma_ngia_cmis, thoigian_bdien = EXCLUDED.thoigian_bdien, bac_thang = EXCLUDED.bac_thang, don_gia_phang = EXCLUDED.don_gia_phang, ngay_hieu_luc = EXCLUDED.ngay_hieu_luc, chi_tiet_gia = EXCLUDED.chi_tiet_gia;
