server:
  port: 8081

spring:
  application:
    name: billing-worker

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:billing_db}?rewriteBatchedInserts=true&prepareThreshold=0
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: WorkerHikariCP
      maximum-pool-size: 100
      minimum-idle: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: false             # Bulk writes commit manually

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          max-active: 100
          max-idle: 20
          min-idle: 5
          max-wait: 2000ms

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: billing-worker-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      max-poll-records: 1000
      properties:
        # Static Membership mapping based on host name
        group.instance.id: worker-pod-${HOSTNAME:local-worker}
        session.timeout.ms: 30000
        max.poll.interval.ms: 300000
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.evn.billing.worker.dto.BillingTaskDto
        spring.json.use.type.headers: false
        fetch.min.bytes: 1048576
        fetch.max.wait.ms: 500
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

  threads:
    virtual:
      enabled: true
